# Generated by Django 5.2.12 on 2026-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_point_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_point_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
