# Generated by Django 5.2.12 on 2026-03-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_yookassa_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
