# Generated by Django 5.2.12 on 2026-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_news_editor',
            field=models.BooleanField(default=False),
        ),
    ]
