# Generated by Django 5.2.12 on 2026-04-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_cleanup_user_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='tx_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_yookassa_id__gt', '')), fields=('payment_yookassa_id',), name='unique_yookassa_payment_id'),
        ),
    ]
