# Generated by Django 5.2.13 on 2026-05-05 23:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_transaction_tx_user_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
                ('token', models.CharField(default=accounts.models.generate_email_verification_token, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pending_registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='pending_reg_email_idx'), models.Index(fields=['username'], name='pending_reg_username_idx'), models.Index(fields=['token'], name='pending_reg_token_idx'), models.Index(fields=['expires_at'], name='pending_reg_expires_idx')],
            },
        ),
    ]
