# Generated by Django 5.2.14 on 2026-06-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_onboarding_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='consent_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='personal_data_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='personal_data_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='terms_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_data_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_data_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
