# Generated by Django 5.2.12 on 2026-03-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
