# Generated by Django 5.2.12 on 2026-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='item_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
