# Generated by Django 5.2.12 on 2026-03-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_price_chat_seller_chat_status'),
        ('collectibles', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='collectibles.item'),
        ),
        migrations.AddField(
            model_name='chat',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='track_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание согласия'), ('seller_agreed', 'Продавец согласен'), ('paid', 'Оплачено, ждём отправки'), ('shipped', 'Посылка в пути'), ('arrived', 'Посылка прибыла'), ('completed', 'Сделка завершена')], default='pending', max_length=20),
        ),
    ]
