# Generated by Django 5.2.12 on 2026-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chat_item_chat_shipped_at_chat_track_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cdek_uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='track_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
