# Generated by Django 5.2.12 on 2026-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_add_cdek_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='buyer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='seller_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
