# Generated by Django 5.2.12 on 2026-04-30 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_add_rating_confirmed'),
        ('collectibles', '0005_remove_item_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status', '-created_at'], name='chat_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['seller', 'status'], name='chat_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_read'], name='msg_chat_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='msg_chat_created_idx'),
        ),
    ]
