# Generated by Django 5.2.14 on 2026-05-08 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_deals_for_existing_chats(apps, schema_editor):
    Chat = apps.get_model('chats', 'Chat')
    Deal = apps.get_model('chats', 'Deal')

    held_statuses = {'paid', 'shipped', 'arrived'}
    for chat in Chat.objects.filter(seller_id__isnull=False, price__isnull=False).iterator():
        buyer_id = (
            chat.participants
            .exclude(pk=chat.seller_id)
            .values_list('pk', flat=True)
            .first()
        )
        escrow_status = 'not_held'
        held_amount = 0
        if chat.status in held_statuses:
            escrow_status = 'held'
            held_amount = chat.price
        elif chat.status == 'completed':
            escrow_status = 'released_to_seller'

        Deal.objects.get_or_create(
            chat_id=chat.pk,
            defaults={
                'buyer_id': buyer_id,
                'seller_id': chat.seller_id,
                'item_id': chat.item_id,
                'subject': chat.subject,
                'item_image': chat.item_image,
                'amount': chat.price,
                'status': chat.status,
                'escrow_status': escrow_status,
                'held_amount': held_amount,
            },
        )


def delete_created_deals(apps, schema_editor):
    Deal = apps.get_model('chats', 'Deal')
    Deal.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_chat_chat_status_created_idx_and_more'),
        ('collectibles', '0005_remove_item_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('item_image', models.CharField(blank=True, max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Ожидание согласия'), ('seller_agreed', 'Продавец согласен'), ('paid', 'Оплачено, ждём отправки'), ('shipped', 'Посылка в пути'), ('arrived', 'Посылка прибыла'), ('completed', 'Сделка завершена')], default='pending', max_length=20)),
                ('escrow_status', models.CharField(choices=[('not_held', 'Не удержано'), ('held', 'Средства удерживаются'), ('released_to_seller', 'Зачислено продавцу'), ('refunded_to_buyer', 'Возвращено покупателю')], default='not_held', max_length=30)),
                ('held_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_deals', to=settings.AUTH_USER_MODEL)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='chats.chat')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='collectibles.item')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_deals', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats_deal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['escrow_status', '-created_at'], name='deal_escrow_created_idx'), models.Index(fields=['seller', 'escrow_status'], name='deal_seller_escrow_idx'), models.Index(fields=['buyer', 'escrow_status'], name='deal_buyer_escrow_idx')],
            },
        ),
        migrations.RunPython(create_deals_for_existing_chats, delete_created_deals),
    ]
