# Generated by Django 5.2.14 on 2026-05-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0005_remove_item_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collectibles.item')),
            ],
            options={
                'db_table': 'item_images',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['item', 'order'], name='item_image_order_idx')],
            },
        ),
    ]
