# Generated by Django 5.2.12 on 2026-04-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='subject',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='topic',
            field=models.CharField(choices=[('site', 'Проблема с сайтом'), ('seller', 'Проблема с продавцом'), ('buyer', 'Проблема с покупателем'), ('payment', 'Проблема с оплатой'), ('no_money', 'Не пришли деньги'), ('cdek', 'Проблема со СДЭК'), ('deposit', 'Проблема с пополнением счёта'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
